export const ON_CHANGE_COUNTY = 'ON_CHANGE_COUNTY';
export const ON_CHANGE_FOCUS_SITE = 'ON_CHANGE_FOCUS_SITE';
export const REQUSET_AQI_PENDING = 'REQUSET_AQI_PENDING';
export const REQUSET_AQI_SUCCESS = 'REQUSET_AQI_SUCCESS';
export const REQUSET_AQI_ERROR = 'REQUSET_AQI_ERROR';



